### ISSUE TITLE
i2c errors on build or npm install

### ISSUE THREAD

**Issue by skipzero** [Agilatech/si1145#1]
I've tried to install both by npm install agilatech/si1145 as well as cloning the repo and building with node-gyp per the instructions in the readme. In both cases I get the same error and not sure how to proceed. I've also tried searching for the error for possible solutions with no real luck.

The main error upon either way to install:

make: Entering directory '/home/pi/SunIOT_PubHub/node_modules/@agilatech/si1145/build'
  CXX(target) Release/obj.target/si1145/I2CDevice.o
In file included from ../I2CDevice.h:27:0,
                 from ../I2CDevice.cpp:16:
/usr/include/linux/i2c-dev.h:37:8: error: redefinition of ‘struct i2c_msg’
 struct i2c_msg {
        ^
In file included from ../I2CDevice.h:26:0,
                 from ../I2CDevice.cpp:16:
/usr/include/linux/i2c.h:68:8: error: previous definition of ‘struct i2c_msg’
 struct i2c_msg {
        ^
In file included from ../I2CDevice.h:27:0,
                 from ../I2CDevice.cpp:16:
/usr/include/linux/i2c-dev.h:89:7: error: redefinition of ‘union i2c_smbus_data’
 union i2c_smbus_data {
       ^
In file included from ../I2CDevice.h:26:0,
                 from ../I2CDevice.cpp:16:
/usr/include/linux/i2c.h:128:7: error: previous definition of ‘union i2c_smbus_data’
 union i2c_smbus_data {
       ^
si1145.target.mk:97: recipe for target 'Release/obj.target/si1145/I2CDevice.o' failed
make: *** [Release/obj.target/si1145/I2CDevice.o] Error 1
make: Leaving directory '/home/pi/SunIOT_PubHub/node_modules/@agilatech/si1145/build'

the npm-debug.log file can be found in this gist:
[npm-debug.log](https://gist.github.com/skipzero/76a3ac640f2bec3f8f3607bbdb061b42)

**Comment by AgilatechSystems** [comment]
Wow, sorry to see this.  This is caused by the inclusion of both header files, linux/i2c.h and linux/i2c-dev.h in the system.  On that platforms we’ve tested on, there has not been a parameter name conflict like the one you’re seeing.

Can you tell me what linux platform and version you using?

Thanks,

Scott

**Comment by skipzero** [comment]
Sure Scott, It's Rpi. a Raspberry Pi, Linux 4.4.38-v7+ armv7l GNU/Linux, debian 8.0 (2016-02-03-raspbian-jessie), in full disclosure, I also had followed these [steps](https://learn.adafruit.com/adafruits-raspberry-pi-lesson-4-gpio-setup/configuring-i2c) as well as added the [Adafruit_Python_pureIO](https://github.com/adafruit/Adafruit_Python_PureIO) module. Which I was able to get the sensor working with. and it was with this [SI1145](http://store.switchdoc.com/grove-sunlight-ir-uv-i2c-sensor/) sensor.

I reckon it's because I had tried the adafruit plugin first and now have those to conflict with your package?

**Comment by AgilatechSystems** [comment]
Turns out there is a problem when i2c-tools provides the i2c-dev header.  In this unusual case, symbols in i2c.h are redefined.  We implemented a workaround which only includes i2c header if all the symbols are not already defined.  

This workaround will likely raise some type warnings in the build which can be ignored.

**Comment by skipzero** [comment]
So that means it'll work!? 😄 
I'll make a test script this evening if that's the case. I just wasn't sure it even completed with the errors I had gotten last night. 
Thanks and sorry for the back and forth.
